# The testing notebook

Idea of this notebook is to better understand the dataset and how to use it. There aren't any final solutions here.

Useful imports

In [1]:
#%pip install fastf1
#%pip install python-dotenv

import os
import fastf1
from dotenv import load_dotenv

## Day 0 - Testing for the size

In [2]:
#Getting account sign in for data
load_dotenv()
os.environ['F1_USERNAME'] = os.getenv('F1_USERNAME')
os.environ['F1_PASSWORD'] = os.getenv('F1_PASSWORD')

#Cashe configuration
fastf1.Cache.enable_cache('data/cache')

#We take our planed qualifying
session = fastf1.get_session(2026, 'Singapore', 'Q')
session.load()

#Laps check
laps = session.laps
print("Laps shape:", laps.shape)
display(laps.head())

/home/zero/miniconda3/envs/IDS/lib/python3.13/site-packages/fastf1/req.py:251: FutureWarning: `.enable_cache` is deprecated and will be removed in a future version. Use `.configure` instead.
  warnings.warn("`.enable_cache` is deprecated and will be removed in a "
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.9.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['3', '16', '44', '12', '1', '63', '81', '10', '30', '41', '27', '87', '31', '55', '5', '43', '14', '23', '18', '11', '77', '6']

Laps shape: (363, 31)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:19:18.397000,VER,3,NaT,1.0,1.0,0 days 00:17:21.662000,NaT,NaT,0 days 00:00:46.603000,...,False,Red Bull Racing,0 days 00:17:21.662000,2026-10-10 13:34:13.409,12,NaN,False,,False,False
1,0 days 00:20:51.638000,VER,3,0 days 00:01:33.241000,2.0,1.0,NaT,NaT,0 days 00:00:27.674000,0 days 00:00:39.190000,...,False,Red Bull Racing,0 days 00:19:18.397000,2026-10-10 13:36:10.144,21,NaN,False,,False,True
2,0 days 00:23:10.836000,VER,3,0 days 00:02:19.198000,3.0,1.0,NaT,0 days 00:22:33.185000,0 days 00:00:31.359000,0 days 00:00:41.700000,...,False,Red Bull Racing,0 days 00:20:51.638000,2026-10-10 13:37:43.385,1,NaN,False,,False,False
3,0 days 00:41:24.005000,VER,3,NaT,4.0,2.0,0 days 00:39:16.230000,NaT,NaT,0 days 00:00:47.833000,...,True,Red Bull Racing,0 days 00:23:10.836000,2026-10-10 13:40:02.583,1,NaN,False,,False,False
4,0 days 00:42:56.297000,VER,3,0 days 00:01:32.292000,5.0,2.0,NaT,NaT,0 days 00:00:27.363000,0 days 00:00:38.840000,...,True,Red Bull Racing,0 days 00:41:24.005000,2026-10-10 13:58:15.752,1,NaN,False,,False,True

In [3]:
#Kurvide info saamine
circuit_info = session.get_circuit_info()
corners = circuit_info.corners
display(corners)

               X            Y  Number Letter       Angle     Distance
0     431.132652  3476.576339       1          40.098991   392.951373
1    -195.214034  3722.206835       2        -116.338121   464.579726
2    -779.754260  4085.899970       3         108.318126   531.883815
3   -1000.248495  2762.565807       4        -159.825842   677.706777
4    -704.275136   290.498744       5         -56.175072   954.987736
5   -4914.428676   446.078774       6         -99.405340  1372.227678
6   -8210.484032  2141.918937       7          84.288029  1738.793166
7   -9608.455015   545.234452       8        -137.554884  1970.263056
8  -11035.325463  1643.483060       9         -77.178353  2158.269656
9  -13197.999977 -1883.988437      10        -182.928561  2592.258909
10 -12225.258327 -3008.978817      11          21.972981  2752.905356
11 -11972.752928 -3759.247104      12        -133.164260  2832.841047
12 -10795.164154 -4903.606508      13         -96.042990  2996.473694
13  -9087.216472    75.608171      14         273.562616  3560.868140
14  -7370.032740 -1290.333574      15         247.803928  3791.551111
15  -2544.274083 -1747.779915      16          41.594525  4277.443106
16  -2205.492525 -2401.410453      17          48.421856  4354.830807
17    386.842772 -2657.589497      18          99.549741  4601.548926
18   1136.566184 -1839.636022      19         -14.648660  4725.024722